language: java
sudo: false
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
- openjdk6
before_install:
- mkdir /usr/share/ca-certificates/extra
- wget -k http://www.tbs-x509.com/COMODOECCCertificationAuthority.crt > /usr/share/ca-certificates/extra/comodo-ca.crt
- dpkg-reconfigure ca-certificates
install:
- ./gradlew assemble
script:
- ./gradlew clean build -PossrhUsername= -PossrhPassword=
