language: java
sudo: false
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
- openjdk6
install:
- ./gradlew assemble -PossrhUsername= -PossrhPassword=
script:
- ./gradlew clean build -PossrhUsername= -PossrhPassword=
