language: java
sudo: required
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
- openjdk6
before_install:
- sudo mkdir /usr/share/ca-certificates/extra
- wget -k http://www.tbs-x509.com/COMODOECCCertificationAuthority.crt > /tmp/comodo-ca.crt
- sudo mv /tmp/comodo-ca.crt /usr/share/ca-certificates/extra/comodo-ca.crt
- sudo dpkg-reconfigure ca-certificates
install:
- ./gradlew assemble
script:
- ./gradlew clean build -PossrhUsername= -PossrhPassword=
